---
- hosts: ops

  vars:
    cli:
      host: 172.17.0.5
      port: 22
      username: netop
      password: netop

  tasks:
    - name: set hostname with file lookup
      ops_template:
        src: ./ops_switchrole.json
        backup: yes
      become: yes
