---
- name: print JSON input for this play
  debug: >
    msg="{{ lookup('template', 'main.j2') }}"
  when: ops_debug is sameas true

- name: configure the switch
  become: yes
  ops_template:
    src: "{{ lookup('template', 'main.j2') }}"
    backup: true
    force: true
  when: ops_bridges is defined or ops_vrfs is defined
  register: ops_result

- name: result from the switch
  debug: var=ops_result
  when: ops_debug is sameas true
